### ISSUE TITLE
Collection of bugs I encountered when installing BCML from scratch

### ISSUE THREAD

**Issue by BitGrub** [NiceneNerd/BCML#121]
BCML version 3.3.2, according to the about page.

Sorry in advance for the really long and whiny post. Just wanted to be thorough in my findings.

Firstly, the "installer" was a nightmare, and the only way I got it to work (after re-extracting the archive a million times and trying again) was to only have the "Make start menu shortcut" option enabled. Any other combination of options would result in a dialogue box that claimed it was successfully installed, but then nothing would happen when trying to launch it (no error, no bcml window, just two python processes that never close themselves in task manager. I even restarted my PC and tried again a few times. Still nothing.).
Enabling "create desktop shortcut" would give me an error message instead of a fake success message ("could not create .lnk" no reason given. I suspect it could be because I have Microsoft's OneDrive enabled)

And after all that, there's no indication **or any reason to believe** that the "install" location is just _wherever you extracted the setup.exe_, so deleting it from my _downloads_ (read: not _program files_ ) folder meant I had to start all over.

After getting it to launch, mostly everything worked wonderfully. Great tool, lots of love, you guys are doing god's work ❤. But I did encounter some more oddities nonetheless.
Some mods are arbitrarily hidden from the in-app gamebanana browser. Namely, "Linkle Dialogue Fix" and "Shrek Hinox". They both have .bnp versions available, and neither are NSFW, so I'm baffled why those two (and probably more) are hidden. I have yet to test if they're working because apparently I can't find a damn hinox or gendered dialogue box to save my life.

Finally, the "Thomas The Tank Engine" mod installed successfully, I tested it and it's working in-game, but it's listed as "Bowsette BOTW" (???) in BCML. Thumbnail, functionality and description are all correct, just the name is wrong. Problem persists through reinstallation (BCML couldn't delete it, I had to do it manually and then remerge), so this **_might_** be an issue with the mod itself, rather than BCML, but I would appreciate some guidance on how to rename it manually without screwing it, please.

I suspect that both of the above post-install problems could be caused by caching errors, but have no way to know for sure.

**Comment by NiceneNerd** [comment]
Most of the installer issues (except the OneDrive thing) should be fixed in the new installer build, which is included in the current GitHub release but not in the GB download. 

As for the missing mods, I took a look at them. For Shrek, the problem is that the mod is made wrong: it capitalizes the `Content` folder, which BCML doesn't fully support (and will not, since too much stuff it has to do is case-sensitive and working around that would be a huge pain). For the Linkle Dialogue Fix, it looks like the problem is actually an oversight in how old (BCML 2.*x*) BNPs are identified, as it misses them if they include no full game files but only merger logs, so that can be fixed pretty easily.

For Thomas the Tank engine the problem is indeed in the mod's own `rules.txt` file. BCML will have updated it to an `info.json` for BCML 3, so you can use Explore on the mod to find the file, and then just edit the name.

**Comment by BitGrub** [comment]
Thanks for the quick and thorough reply, and thanks for explaining to me how to rename the mod
