### ISSUE TITLE
does not recognize the folders

### ISSUE THREAD

**Issue by jekkkk** [NiceneNerd/BCML#124]
BCML does not recognize E:\atmosphere\contents\01007EF00011E000\romfs as the base+update directory but does count E:\atmosphere\contents\01007EF00011f001\romfs as the DLC.

**Comment by jekkkk** [comment]
switch btw

**Comment by NiceneNerd** [comment]
Your game dump is basically never in your Atmosphere contents folder; that's used for mods. Dump your game first, then point to your dump.

**Comment by iMonZ** [comment]
> Your game dump is basically never in your Atmosphere contents folder; that's used for mods. Dump your game first, then point to your dump.

Would be great if you could update the Installation documentation because there are currently useless.
Not one single information is useful in the installation documentation inside GitHub (except if you compile it yourself) and important information is just missing.
But still thanks for the mod 
(btw why do you need dotNET? I haven't found it inside the python script)

**Comment by NiceneNerd** [comment]
@iMonZ 
> Would be great if you could update the Installation documentation because there are currently useless.  
> Not one single information is useful in the installation documentation inside GitHub (except if you compile it yourself) and important information is just missing.

You can also follow the instructions for a pip install. I removed the Windows setup bundle instructions because I will soon be removing the Windows setup bundle method entirely to support pip as the primary installation method. At that time I will also add a new YouTube tutorial for doing a pip install.

> (btw why do you need Visual C++? I haven't found it inside the python script)

It is required by some of the Python libraries, primarily `oead`, which provides bindings to code written in C++.

**Comment by iMonZ** [comment]
> @iMonZ
> 
> > Would be great if you could update the Installation documentation because there are currently useless.
> > Not one single information is useful in the installation documentation inside GitHub (except if you compile it yourself) and important information is just missing.
> 
> You can also follow the instructions for a pip install. I removed the Windows setup bundle instructions because I will soon be removing the Windows setup bundle method entirely to support pip as the primary installation method. At that time I will also add a new YouTube tutorial for doing a pip install.
> 
> > (btw why do you need Visual C++? I haven't found it inside the python script)
> 
> It is required by some of the Python libraries, primarily `oead`, which provides bindings to code written in C++.

Thank you for the answer.
The plan sounds great!
