### ISSUE TITLE
Map Log not generated for Option

### ISSUE THREAD

**Issue by CEObrainz** [NiceneNerd/BCML#242]
When creating a BNP that has map changes in both the base mod and one of it's options, the option does not generate the map logs. 

Map Logs will be generated if the base mod has no map changes, but when both contain them only the base mod generates them.

As a workaround I can build the option as its own mod, then copy/paste the map logs into the combined bnp-with-options.

**Comment by GingerAvalanche** [comment]
Logs are generated for any files that exist in the **temp** options folder at time of log generation.

There's a not-so-obvious quirk to the option parser, in that it does not copy files from the mod options folder to the temp options folder if those files are unchanged from either the vanilla file or the base mod file of the same path. It does this because there's no real reason to install the same file twice; it'd just be "overriding" things with the values they already have.

#250 reports this behavior when it results in no files being copied to the temp options folder, but there's no real good way to communicate it otherwise.
