### ISSUE TITLE
Update Directory Not Recognized

### ISSUE THREAD

**Issue by ohyousoretro** [NiceneNerd/BCML#263]
I'm doing a new install of BCML, but for whatever reason the Update directory won't go green. When I put the CEMU directory in, it auto populates the other fields. I've opened the Update directory from CEMU and tried copying and pasting that path, despite it being exactly the same as the auto populated one, and nothing. Browse doesn't work. I've tried every folder in there and nothing will work. The update is the only problem I'm having. I'm using CEMU 1.26.1, I've installed the game, the update, and the DLC.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/45382678/153940134-8bc92a4c-4da7-435f-859f-b168a6eb4097.png">

**Comment by GingerAvalanche** [comment]
![Capture](https://user-images.githubusercontent.com/32864080/153944843-d2369d13-58b7-4cc2-8165-3e937e308d2c.PNG)

`bcml` searches for `update_dir / "Actor" / "Pack" / "FldObj_MountainSnow_A_M_02.sbactorpack"` in order to validate. If that file doesn't exist at that path, it won't put the checkmark.

Github issues are for bugs with the program. For general bcml troubleshooting, please ask in the discord server. https://discord.gg/vPzgy5S

**Comment by Torphedo** [comment]
Hitting Update Directory in Cemu brings you to the folder containing `content`. Add `content` to the end of the path and it should be fine.
