### ISSUE TITLE
"No storage folder available" error. Followed all the video instructions correctly.

### ISSUE THREAD

**Issue by TheD0ct0r101** [NiceneNerd/BCML#307]
Error is as follows when running bcml.exe:

[2022-04-16 17:17:49] Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\bcml.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\python38\lib\site-packages\bcml\__main__.py", line 99, in main
    configure_cef(debug)
  File "c:\python38\lib\site-packages\bcml\__main__.py", line 51, in configure_cef
    cache = util.get_storage_dir() / "cef_cache"
  File "c:\python38\lib\site-packages\bcml\util.py", line 543, in get_storage_dir
    raise FileNotFoundError("No storage folder available")
FileNotFoundError: No storage folder available

**Comment by GingerAvalanche** [comment]
If you haven't run BCML successfully and set its settings yet, then the storage folder is the same as the data folder. On windows, that folder is `%LOCALAPPDATA%/bcml`

If that folder doesn't exist, bcml tries to create it. If bcml then says the folder isn't available, that's because bcml didn't have the permissions to create that folder. Create the folder yourself, run bcml as administrator, or lighten the UAC setting level and it should work.

This only applies to windows. You didn't specify your environment, but I've never seen this happen on Linux

**Comment by TheD0ct0r101** [comment]
> 

I just checked local appdata, the bcml folder is there. So im guessing its the UAC. Thing is, im running it as administrator and it's still giving the exact same error.

**Comment by TheD0ct0r101** [comment]
Update; I deleted the bcml folder and ran the script as admin again. The program opened this time. It looks like I can now move my data folder directory somewhere easier to access for both me and BCML. Thanks for your assistance!
