### ISSUE TITLE
Saving mods causes character issues in settings.xml

### ISSUE THREAD

**Issue by slashiee** [NiceneNerd/BCML#32]
Whenever using BCML, I've noticed that Pokkén Tournament becomes a mess of characters. The more you use the program (since it saves to settings.xml), the worse it gets.
<img width="230" alt="2020-01-27_17-46-50" src="https://user-images.githubusercontent.com/15317421/73229046-44b0e980-412d-11ea-9391-36fea006d1c3.png">
<img width="754" alt="2020-01-27_17-47-33" src="https://user-images.githubusercontent.com/15317421/73229048-467aad00-412d-11ea-8bf0-9fdac9bda544.png">

[settings.zip](https://github.com/NiceneNerd/BCML/files/4120262/settings.zip)

**Comment by GingerAvalanche** [comment]
This is because of the accented e in Pokken. Older versions of BCML didn't read the text as unicode, so the unicode bytes resulted in a bunch of junk characters that contained more unicode characters that would result in more junk, etc. As I understand it, this was fixed back in bcml2.6.0 (it's on 2.7.3 now) so update BCML and you should be fine. Also, delete that entry from your settings file entirely and cemu should regenerate it normally.

**Comment by NiceneNerd** [comment]
Ginger is right, this should be fixed now. Let me know if it's not.

**Comment by slashiee** [comment]
Running 2.7.3, it has the issue for me.
<img width="641" alt="2020-02-04_10-28-50" src="https://user-images.githubusercontent.com/15317421/73774619-25bbe400-4739-11ea-92fd-5b04344c0ac1.png">
