### ISSUE TITLE
Suggestion: WUA/ZArchive support

### ISSUE THREAD

**Issue by Makonede** [NiceneNerd/BCML#330]
I recently updated to Cemu 1.27.0b and converted my game files to a WUA. This, however, sent BCML back into the initial setup menu, as the previous game paths were now invalid. It would be nice if BCML could implement ZArchive and allow for game file extraction from a WUA instead of needing to manually re-extract the game files just to use BCML.

**Comment by ArchLeaders** [comment]
Do you mean WUP?
Either way, any extraction would make merging considerably slower. And if you're suggesting that BCML should cache the game files for future use, you may as well just extract them anyway.

Also, ZArchive is android (unless I am mistaken), so it probably would not be easy or practical to implement it.

**Comment by Torphedo** [comment]
No, WUA is a new archive format Cemu recently implemented so that people can store Wii U games as a single ROM file. It's probably not feasible to implement though, BCML would probably to try to unpack it into memory or something. The alternative is unpacking to a temp directory every time, which would kill SSD longevity and slow the whole process down

**Comment by ArchLeaders** [comment]
Ahh, I see. And yeah, makes sense that they might be pirates too. ~~I don't think we need to make it easier for them.~~

**Comment by GingerAvalanche** [comment]
Piracy *is* one major concern. Single compressed archives are much easier to transport than an entire game dump (which is the design philosophy behind the bnp file type, in fact)

However, there's a much bigger obstacle: ZArchive is C++. It would need Python bindings written for it, or bcml wouldn't be able to use it.

bcml *could* just use a Windows command to tell the ZArchive exe to extract the WUA and use those files, but then you'd have an entire extracted game dump sitting there.

bcml *could* then delete that game dump, but that'd just make the install process take longer each time you ran it, so the smart thing to do would be to leave those files there.

But then you'd have a separate game dump just sitting there on your hard drive, "forever," so that bcml could use it. And at that point, you might as well just leave the extracted dump there, yourself - you'd gain no benefit from bcml handling it.
