### ISSUE TITLE
BCML can't install mods after shortcut randomly broke

### ISSUE THREAD

**Issue by Cloakam** [NiceneNerd/BCML#359]
I was trying to install mods when randomly it broke. It wouldn't install mods and when I closed it to try and restart it, it wont let me open it again and the icon disappeared. I tried restarting but it didn't do anything. I checked task manager just in case there were duplicate applications but there isn't.

**Comment by NiceneNerd** [comment]
Run `bcml-debug` and post the output

**Comment by Cloakam** [comment]
That fixed bcml! Thank you!

**Comment by Cloakam** [comment]
Theres still a few issues, the one I said in the previous comment, and that installing mods goes forever, so to finish installing them, I have to restart bcml.

**Comment by NiceneNerd** [comment]
Run with `bcml-debug` and post the output when a mod hangs forever

**Comment by Cloakam** [comment]
VERBOSEBcmlMod(name="Crafting Project", path="C:/Users/AJ Addis/AppData/Local/bcml/mods/0117_CraftingProject", priority=117)
VERBOSEBcmlMod(name="[LINK] Ancient Armor Concept 1.8", path="C:/Users/AJ Addis/AppData/Local/bcml/mods/0100_LINKAncientArmorConcept1.8", priority=100)
VERBOSEBcmlMod(name="House Enhancements - Link", path="C:/Users/AJ Addis/AppData/Local/bcml/mods/0116_HouseEnhancements-Link", priority=116)

**Comment by GingerAvalanche** [comment]
@Cloakam Found a temporary workaround:

Go into your BCML settings
Check the box for Use BCML without a Cemu installation
Enter a path into the Merged Export Directory field (doesn't matter what folder you put, you can use your cemu graphics pack folder if you have cemu, or your documents if not)
Save your settings
Go back into your settings
Uncheck the box for Use BCML without a Cemu installation
Save your settings
Install mods

For my and Nicene's notes: The issue seems to be that Rust thinks the default for export_dir - which should be PathBuf::new, is instead null. Not sure how to respond to this, since it doesn't seem to do this for other fields, and the erroring functions don't even seem to be referring to `export_dir`

**Comment by Cloakam** [comment]
>
