### ISSUE TITLE
"Installing Mod" Forever

### ISSUE THREAD

**Issue by gigglebunsuv** [NiceneNerd/BCML#427]
I recently installed BCML and when I go to install a mod, it just gets stuck at the Installing Mod screen. I also did notice, that if I left it long enough and simply reset, the mod appears to have been installed. But obviously there is no way for me to see the status of the installation, so it's a shot in the dark on whether or not that method would work.

**Comment by NiceneNerd** [comment]
Run using `bcml-debug` and see what the console says while installing

**Comment by jedinjapan** [comment]
I had the same issue, and it stemmed from BCML initializing on each boot. In my experience, I had to run BCML as administrator at least one to allow it to make the initial settings file in the install location. YMMV, but I have taken to running BCML as admin now and it removed a number of issues.

**Comment by GingerAvalanche** [comment]
The settings file only goes in the install directory if you're running in portable mode, and there's no reason to run it in portable mode from a protected location. Otherwise, it goes in the data directory, which is, by default, in `%LOCALAPPDATA%` - which is unprotected, since it's entire reason for existence is to store unprotected app data.

Closing this because there was no response from the original author for months. Presumably, it's either been fixed or bypassed.
