### ISSUE TITLE
Arch linux error

### ISSUE THREAD

**Issue by Slapspat** [NiceneNerd/BCML#433]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
 

This is what I get trying to install it. I have numpy and pyproject.toml-based installed. Just not wanting to work.

**Comment by HGStone** [comment]
use python 3.8

**Comment by Slapspat** [comment]
I have python 3.10 currently installed and did try to install 3.9 instead. My arch linux came with python 3.10 by default.

**Comment by v-fox** [comment]
> Python 3.10 is not supported on any OS. I suggest using pyenv.

But why do you force numpy-1.19.5 that doesn't compile with python-3.10 instead of numpy-1.21.6 that does ?

**Comment by NiceneNerd** [comment]
A'ight then

But IDK what you mean about "dependency hell you will never see on Linux" when BCML was developed primarily on Linux.

**Comment by v-fox** [comment]
> A'ight then

Actually, setting up venv that makes `maturin develop` run doesn't work either because it also uses latest available rust (1.64) in the distro which rstb-0.3.2 doesn't like just the same. And [pre-compiled Linux binary from pip is broken](https://github.com/NiceneNerd/BCML/issues/436). Running Windows version from pip in wine also doesn't work because it wants working MSVC compiler environment which is non-trivial to set up. So, there is no way to compile or run it until you fix up compilation dependencies or recompile pip package with safe generic flags.

> But IDK what you mean about "dependency hell you will never see on Linux" when BCML was developed primarily on Linux.

I don't know what kind of Linux you've been using but in 20 years of my experience you either put 1 command to system packet manager to get a package from automated build-server or install dependencies also with 1 command and then run a build-script which will make an app that uses all current system dependencies and get installed in proper, standardized, easily maintainable shared places.
There is a reason why standard distro policy is "compile everything against latest versions of everything, older dependencies in repositories only for badly maintained irreplaceable apps that a distro maintainer can't easily fix to port unto current dependencies without developers unscrewing their unportable code themselves". Meaning that any "< $version" directive is compromise, not a normal thing to do.

What you will NOT do is setting up entire hundreds or thousands of megabytes of toolchain for an outdated compiler fork (rust is just bastardized version of clang with vendor-locking on cargo online infrastructure and overly hardcoded build-scripts with inexplicable locking of modification via mandatory checksum checking) with bell and whistles & libraries from a third-party repository (cargo/pip) to build whole bunch of big fat shared libraries, that are not actually shared with anything, into sandbox for a single one-time use utility. It wouldn't be such a mess if it was not a mixed app of interpreted code + pre-compiled binary code that could only be compiled with the worst compiler in modern history due to being targetted at throwing whole Linux convention out to mimic worst parts of Windows, MacOS and Android software management.

**Comment by NiceneNerd** [comment]
Nothing about BCML is normal. The entire thing is a compromise and a hack, built progressively using whatever tools happened to be available in whatever way could be forced to work.

You complain about an awful lot of stuff, but none of it matters unless you want to volunteer to rewrite BCML from scratch.

**Comment by GingerAvalanche** [comment]
@v-fox  You seem very intent on leaving py310 as your version, instead of installing py38 and piping the pip command through the 3.8 executable, which is the supported way of installing bcml.

**Comment by v-fox** [comment]
> You seem very intent on leaving py310 as your version, instead of installing py38 and piping the pip command through the 3.8 executable, which is the supported way of installing bcml.

@GingerAvalanche 
I was using python 3.9 (both a recommended version AND 1.10, current distro version, for that supposedly Linux-centric software) for test with pipx, venv and Windows version in pip, so how about you get familiar with situation of the issues instead of making irrelevant excuses ? The fatal issues are with the pre-compiled binary and bad rust dependency, the way bcml is laid out just makes it almost undebugable and bit-rotting dependencies is just one consequence of that.

> Nothing about BCML is normal. The entire thing is a compromise and a hack, built progressively using whatever tools happened to be available in whatever way could be forced to work. And tons of dependencies are held back for reasons outside my control.

> You complain about an awful lot of stuff, but none of it matters unless you want to volunteer to rewrite BCML from scratch.

@NiceneNerd 
I'm complaining because, even after following all of your instructions and doing bunch of my own testing, it's now completely unusable, so I can't fix BOTW with a single mod that would make it orders of magnitude more playable because literally all methods of installation fail. You admit yourself that it was due to your design. Well, because of your choice of python/rust and third-party cargo packaging, it's almost impossible to debug and fixed by users and distro maintainers, **you have to fix it on the side of PyPi, be replacing the binary, and by the side of cargo**, be I don't know what with the rust dependencies. I'm (**and everyone except you**) physically unable to do that as a user and distro packager due to how those third-party services work.

For now, I suggest figuring what bad compile options is going into the PyPi-packaged Linux binary, my bet is on avx2 in some statically linked dependency, like libz-ng. This likely be easier then figuring out cargo's hardcoded uncompilable dependency crap.

**Comment by HGStone** [comment]
you can fix your problem by using Windowd

**Comment by v-fox** [comment]
> you can fix your problem by using Windows

Oh, fantastic. Another knee-jerk fanatical reaction ? Are we going to just do juvenile trolling here ?

It's "my problem" on discussion here, it's YOUR problem, as it is your issue tracker for your software to which you seem to be a contributor to. The author asked what is the Linux problem on his "developed primarily on Linux" software and I answered factually and honestly, no need to bring the circus around it. 

Unless it's not clear, I actually fixed the original reported issue here about python dependencies and made it work on all version of python3, it's the binary that is the ultimate hurdle. Not like any facts matter to the cheerleading squad.

Also, the Windows installation of pre-compiled bcml also seems to be pulling numpy dependency that wants to compile something all the same. I've read up on complains on gamebanana and it seems not all is well there either. So how about keeping this discussion about software and not your emotional reactions to my the personality as a messenger ? And don't go pulling ages old "but I'm helpful with my trolling" excuse, I've been around Linux community for 20 years, I've seen this "but Windows though" quip hundreds of times.

**Comment by HGStone** [comment]
ah yes, a contributor, I added the words "or info.json" on the install mod pop-up.

here's an idea, use python 3.8 through pyenv as recommended since  3.9 seems to o ly work for some people, which apparently you are not one of them.

**Comment by ArchLeaders** [comment]
> > You seem very intent on leaving py310 as your version, instead of installing py38 and piping the pip command through the 3.8 executable, which is the supported way of installing bcml.
> 
> @GingerAvalanche I was using python 3.9 (both a recommended version AND 3.10, current distro version, for that supposedly Linux-centric software) for test with pipx, venv and Windows version in pip, so how about you get familiar with situation of the issues instead of making irrelevant excuses ? The fatal issues are with the pre-compiled binary and bad rust dependency, the way bcml is laid out just makes it almost undebugable and bit-rotting dependencies is just one consequence of that.
> 
> > Nothing about BCML is normal. The entire thing is a compromise and a hack, built progressively using whatever tools happened to be available in whatever way could be forced to work. And tons of dependencies are held back for reasons outside my control.
> 
> > You complain about an awful lot of stuff, but none of it matters unless you want to volunteer to rewrite BCML from scratch.
> 
> @NiceneNerd I'm complaining because, even after following all of your instructions and doing bunch of my own testing, it's now completely unusable, so I can't fix BOTW with a single mod that would make it orders of magnitude more playable because literally all methods of installation fail. You admit yourself that it was due to your design. Well, because of your choice of python/rust and third-party cargo packaging, it's almost impossible to debug and be fixed by users and distro maintainers, **you have to fix it on the side of PyPi, be replacing the binary, and by the side of cargo**, by I don't know what with the rust dependencies. I'm (**and everyone except you**) physically unable to do that as a user and distro packager due to how those third-party services work.
> 
> For now, I suggest figuring what bad compile options is going into the PyPi-packaged Linux binary, my bet is on avx2 in some statically linked dependency, like libz-ng. This likely be easier then figuring out cargo's hardcoded uncompilable dependency crap. Again, can't do anything about it without even knowing what versions and configurations of cargo/rust were YOU using.

@v-fox this sounds like you are lodging a complaint for something you paid for, and therefore must work. Don't forget this is free software maintained and written in **free time**, it never needs to work nor needed to. It's a massive project, literally designed to do something that was never meant to be done.

If something doesn't work, you can't really blame the developers for doing, or not doing something **for free, in their free time**, people make mistakes, and it's not their **job** to fix them. They're trying their best to make everything work for a wide variety of users on different platforms, and have done an amazing job as far as I'm concerned, given what this software does, and requires.

As far as fixing your issue, try using python 3.7 or 3.8 and install using pip as recommended by @GingerAvalanche.

And sorry if I sound annoyed, I just find far too many people coming and complaining about the software they are getting for free, not to mention also getting free support. Remember, no one here is designated to help you.

> It's "my problem" on discussion here, it's YOUR problem, as it is your issue tracker for your software to which you seem to be > a contributor to. The author asked what is the Linux problem on his "developed primarily on Linux" software and I answered > factually and honestly, no need to bring the circus around it.

And yeah, as HG just stated, he and I are just contributors cause we found a bug and fixed it. It doesn't make us part of some, non-existent "support team", we just like what the devs do, and wanted to help out.

**Comment by GingerAvalanche** [comment]
> Unless it's not clear, I actually fixed the original reported issue here about python dependencies and made it work on all version of python3

It actually wasn't clear.

Since you seem so proud of your 20 years of Linux community membership, you could do what Linux is famous for, and leverage the advantages of open-source development by contributing.

Either way, this issue was solved days ago and has become little more than mud slinging at this point, so I'm closing it out.
