### ISSUE TITLE
Remerging removes all graphicpacks

### ISSUE THREAD

**Issue by HyperSilver69** [NiceneNerd/BCML#438]
Title says enough, No mods were installed so I went into settings.json and changed "export_dir" to `"export_dir": "D:/Emulators/Cemu/graphicPacks",`. When remerging, this just completely wipes all the packs, including the community ones with enhancements.

**Comment by HyperSilver69** [comment]
Also, somtimes one of the installed mods just randomly gets their directory swapped to said folder.
![afbeelding](https://user-images.githubusercontent.com/91153148/197415630-2ae0a381-c5e0-4b69-8b65-2ebc00d2832e.png)

**Comment by HyperSilver69** [comment]
Something that seemed to have fixed is this: `Go to the settings menu, and check the box called "Disable Links for Master Mod"
Go to the Mods Menu, select Second Wind and click the circle arrow Icon to re-merge the mod into your cemu installation.
Click Save
Close BCML
Re-open BCML, go to settings, and uncheck the "Disable Links for Master Mod"
Go to the Mods menu and re-merge the Second Wind Mod again using the Circle Arrow Icon
Click Save
Close BCML`
However, the random directory swap is still unclear. And sure this might be a fix but the issue is still there and requires googling to fix, so it's a bug.

**Comment by GingerAvalanche** [comment]
The export directory is the name of the folder inside which to put `content` - it’s supposed to be a new, empty folder.

BCML hides the export directory setting when in Cemu mode because an empty export directory tells BCML to export to `[cemu_dir]\graphicPacks\BreathOfTheWild_BCML` - you can either manually set your export directory to that, or just delete the setting text and BCML will use it on its own.

The other thing you mentioned, I don’t *quite* understand, but it sounds as if you don’t understand the concept of symbolic file/folder linking and that BCML is working as intended.
