### ISSUE TITLE
When installing any mod, it gives an error

### ISSUE THREAD

**Issue by 01-ADEK-10** [NiceneNerd/BCML#49]
Оn first installation, everything went well.
But after disabling the mod and re-enabling, this error began to appear.
![error](https://user-images.githubusercontent.com/47279655/81378564-b38cde00-9131-11ea-91eb-ac518f697231.jpg)
Please, help

**Comment by GingerAvalanche** [comment]
Copy of #38
Fixed by #42, but that PR isn't (and probably won't be) pulled in because the next release of bcml will be bcml3 which already has the fix integrated into it.

If you want to fix it yourself, you can incorporate the changes from https://github.com/NiceneNerd/BCML/pull/42/commits/c2b1bded32a050e9ca35ca1352a41526c1f7988b into your files.

**Comment by 01-ADEK-10** [comment]
> If you want to fix it yourself, you can incorporate the changes from [c2b1bde](https://github.com/NiceneNerd/BCML/commit/c2b1bded32a050e9ca35ca1352a41526c1f7988b) into your files.

I made changes, but it didn’t help

![still error](https://user-images.githubusercontent.com/47279655/81385324-5a2aac00-913d-11ea-9643-4f00751c481f.jpg)

![still error2](https://user-images.githubusercontent.com/47279655/81385795-2734e800-913e-11ea-8181-1bf312921e10.jpg)

**Comment by NiceneNerd** [comment]
Where exactly is the file you edited?

**Comment by 01-ADEK-10** [comment]
> Where exactly is the file you edited?

Installed the program in Program Files
Both files are here
C:\Program Files\BCML\bcml

**Comment by NiceneNerd** [comment]
Those files won't actually have effect. You'll need to edit them in `C:\Program Files\BCML\pkgs\bcml`

**Comment by 01-ADEK-10** [comment]
It worked!!! Thanks

**Comment by GingerAvalanche** [comment]
Make sure you save the changes to those files (the * in the filename in your editor implies you didn't save the changes) and then close and reopen bcml in order to make bcml reload those files with the changes.

That error is happening because it's still reading `with setpath.open('r') as setfile:` on line 250 of `install.py`. Once the change has been properly saved and loaded into the program, that error will go away.
