### ISSUE TITLE
Always remove unused flags MarioClubTestDungeon_ and _SmallKey02-09

### ISSUE THREAD

**Issue by Waikuteru** [NiceneNerd/BCML#501]
I highly suggest to always delete all MarioClubTestDungeon_ and all _SmallKey02-09 flags when merging because they are unused. If you take my Randomizer mod for example where it deletes those, and you take another mod that didn't delete them, they get merged back and that's bad because there is a limit to how many flags can be stored before memory issues/crashing.

**Comment by GingerAvalanche** [comment]
Regarding the issue name and your stated suggestion: no. This is a mod merger. It merges changes from mods. It does not make its own changes to game files. (The RSTB is a bit of an outlier, because BCML *has* to generate its own values for that, otherwise files modified by multiple mods would not work together, and the merging of the mods wouldn't work very well. )

Regarding the bug you're reporting: Please provide some evidence of this claim. Logs of mods that cause this behavior, post-merge flag files, etc. The merger is designed not to do what you're claiming it's doing.

**Comment by Waikuteru** [comment]
I believe it happened it the past, but I can't say for sure if it's happening with the latest version. So you are saying if mod X is deleting the MarioClubTestDungeon_ flags, and is merged with mod Y, they won't be in the final BCML output graphicPack? Is that only true if mod X has highest priority, or does the priority not matter?

**Comment by GingerAvalanche** [comment]
The priority doesn’t matter in the case as you described it.

It would matter if mod Y edited the flag - in which case, if mod Y was loaded after mod X, then mod Y would load the flag back in (which is intended behavior because if mod Y edits the flag without deleting it, then presumably it requires the flag in order to function correctly). However, if mod X was loaded after, it would still delete the flag.

**Comment by Waikuteru** [comment]
Ok, cool. Gotcha.
