### ISSUE TITLE
Wont export mods to graphicspacks on steam deck

### ISSUE THREAD

**Issue by esanscoopsers** [NiceneNerd/BCML#516]
I have followed cryobyte33's tutorial and i just cant get it to work for the life of me. I have symlink disabled and there are no error messages when i install mods. BCML doesn't show up in cemus graphicspacks even though the export directory in settings.json is correct

**Comment by GingerAvalanche** [comment]
I dunno who crybyte33 is, and I generally don't trust tutorials for BCML that were made by people who aren't NiceneNerd, mostly because those tutorials often tell you to do things that made sense for *their* systems, but may or may not make sense for yours. And they don't explain why it worked for them, so it will just leave you more confused as to why it doesn't work for you.

If Cemu is installed permanently (i.e. not a portable installation, installed to the internal drive, etc) then BCML will install mods to your user data because that's where permanent Cemu installs read from.
If Cemu is installed as a portable installation, then its graphic packs will be read from the install location, instead of your user data. In that case, you need to tell BCML to use without a Cemu installation, and then point the merged export directory at `[cemu install location]/graphicPacks/BreathOfTheWild_BCML`

You should only disable symlinks if any of these 3 cases apply to you:
1) Your export location is a removable drive (SD card, flash drive, etc).
2) Your bcml data folder is on a removable drive. (It's set to app data by default, and most people don't move it, so this is unlikely)
3) You've installed Cemu as a portable installation. (There's a quirk of how BCML does non-cemu installs that keeps it from deleting the rules.txt file if symlinks are disabled. Otherwise, the setting for using BCML without a Cemu installation will cause it to delete and not re-create rules.txt, which makes Cemu unable to read the mod)
In all other cases, disabling symlinks does not help you.

As you may have gleaned from point 3, you should also check your Cemu graphic packs to see if the BCML pack has a rules.txt
