### ISSUE TITLE
The MSBT file C:\Users\OLIVER~1\AppData\Local\Temp\tmpfiwfuenm.msbt could not be read

### ISSUE THREAD

**Issue by oliverrook** [NiceneNerd/BCML#64]
I keep getting the above error whenever I try to install *any* mod on BCML on a version later than 3.0.0b22 or later.
I'm not sure what's happening, but I can't seem to install mods anymore on this version, and on version 3.0.0b22 a lot of mods are missing text or certain features. I'm new to modding BOTW, but I for the life of me can't figure out what's going on or find any help on this particular issue.

**Comment by NiceneNerd** [comment]
Did you close this on purpose?

**Comment by oliverrook** [comment]
Yes, I did. Tho I'm still having trouble installing certain mods, but I found a handful that work. Almost all of them work on the previously mentioned version tho.

**Comment by NiceneNerd** [comment]
@oliverrook So, the secret is that those mods which aren't installing now weren't really fully working before. Some of their text edits were silently failing, but you'd only notice if you tried to use those specific texts in game. I changed the behavior because I think in the end it's better to make errors visible rather than invisible. The only real fix is to patch the mod.
