### ISSUE TITLE
Problem locating game content folders

### ISSUE THREAD

**Issue by IamKayrox** [NiceneNerd/BCML#82]
Folder location is imprecise, CEMU has a function to show game, update and DLC folders by right clicking the game inside CEMU, and selecting the game directory, update directory and DLC directory respectively in the context menu, users should be instructed to use those options since there are variations in folder names due to different game versions

**Comment by GingerAvalanche** [comment]
Except this is objectively and subjectively wrong:

Objectively, that method takes you to the wrong folders. The "game directory" option takes you to `base game/code` when the correct folder to choose is `base game/content`. The "update directory" option takes you to `0005000e/101c9X00`, when the correct folder to choose is `0005000e/101c9X00/content`. The "DLC directory option" takes you to `0005000c/101c9X00`, when the correct folder to choose is `0005000c/101c9X00/content/0010`. The most common mistake, currently, is for people to choose the folders that Cemu directs them to, and the directions don't reference that function because it is not the right folder set.

Subjectively, BCML now has a console mode (or rather, "non-Cemu install mode") for those who don't play on Cemu/don't want to install Cemu, and giving directions with Cemu would needlessly complicate things. Sure, two sets of directions could be given, but there's no need to write an entirely separate set of directions for the sake of saving the user a few extra button clicks, when the generic directions work just fine.

One thing I really need to do (assuming it hasn't already been done) is attempt to read Cemu's settings.xml once the user has chosen the Cemu install path, if using Cemu install mode, and then generate the paths from the info contained there. It's been on my to-do list forever, but things keep getting in the way of it.

**Comment by NiceneNerd** [comment]
None of this should be necessary because in the latest release BCML will automatically detect your game folders when your select your Cemu folder, per Ginger's idea that has in fact been recently added. Besides that, the tooltips are long enough as it is and specifically say they're only examples.

I can go ahead, however, and add a note about how you can work with those buttons to the in-app help that no one reads.
